### ISSUE TITLE
AESNI tracking ticket

### ISSUE THREAD

**Issue by karel-m** [DCIT/perl-CryptX#106]
I have created this ticket as an umbrela issue over the following reported troubles:
* https://github.com/DCIT/perl-CryptX/issues/102
* https://github.com/DCIT/perl-CryptX/issues/100
* https://github.com/DCIT/perl-CryptX/pull/103
* https://github.com/DCIT/perl-CryptX/pull/99

Any improvements related to AESNI should go first to libtomcrypt. Once fixed there I will upgrade CryptX to the latest libtomcrypt version (branch develop).

**Comment by karel-m** [comment]
libtomcrypt related issues:
* https://github.com/libtom/libtomcrypt/pull/644
* https://github.com/libtom/libtomcrypt/pull/641

**Comment by karel-m** [comment]
@thesamesam @PyBonnetainNesterenko could you please check CryptX-0.080_010 ?

**Comment by karel-m** [comment]
Try rather CryptX-0.080_012 which contains #107

**Comment by thesamesam** [comment]
I'll give it a look.

**Comment by karel-m** [comment]
Shoutl be fixed in CryptX-0.081 which I have just released.
