### ISSUE TITLE
Make Crypt::PK::ECC::export_key_der optionally export the short form

### ISSUE THREAD

**Issue by manuelm** [DCIT/perl-CryptX#13]
Like with `export_key_raw('public_compressed')` it would be handy to export the key in the short OID form. e.g something like `export_key_der('public_oid')`, `public_named` (based on `OPENSSL_EC_NAMED_CURVE`) or `public_short`.

Looking at the code it's simply calling `ecc_export` instead of `ecc_export_full`. I can also send you a PR if you tell me which keyword you'd prefer.

**Comment by manuelm** [comment]
I just noticed that `ecc_export` doesn't export in PKCS#8 format, however that's the format I'm looking for. So you can probably close this.

I'll look into adding `ecc_export_pkcs8`.

**Comment by karel-m** [comment]
> I'll look into adding ecc_export_pkcs8

OK, maybe already implemented `ecc_import_pkcs8` might give you some ideas.

**Comment by manuelm** [comment]
Turns out PKCS#8 is another, different format...

The format I'm looking for is just the short/defined by OID/asn.1 ECPrivateKey structure. Does it make sense to extend ecc_export to export as short asn.1 if the curve is a named one with a fallback to the current format? Curve names are ambiguous but asn.1 OIDs are not.

**Comment by karel-m** [comment]
First of all it requires extending current `ecc_export_full` to support short form.

Currently we export ASN.1 structure like this:
```
$ openssl asn1parse -inform DER -in test-explicit.priv.der
    0:d=0  hl=4 l= 288 cons: SEQUENCE
    4:d=1  hl=2 l=   1 prim: INTEGER           :01
    7:d=1  hl=2 l=  24 prim: OCTET STRING      [HEX DUMP]:C2F905E70DC1CB84E096AE45157AB0584F14CF2FC50E9C9C
   33:d=1  hl=3 l= 202 cons: cont [ 0 ]
   36:d=2  hl=3 l= 199 cons: SEQUENCE
   39:d=3  hl=2 l=   1 prim: INTEGER           :01
   42:d=3  hl=2 l=  36 cons: SEQUENCE
   44:d=4  hl=2 l=   7 prim: OBJECT            :prime-field
   53:d=4  hl=2 l=  25 prim: INTEGER           :FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFF
   80:d=3  hl=2 l=  75 cons: SEQUENCE
   82:d=4  hl=2 l=  24 prim: OCTET STRING      [HEX DUMP]:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFC
  108:d=4  hl=2 l=  24 prim: OCTET STRING      [HEX DUMP]:22123DC2395A05CAA7423DAECCC94760A7D462256BD56916
  134:d=4  hl=2 l=  21 prim: BIT STRING
  157:d=3  hl=2 l=  49 prim: OCTET STRING      [HEX DUMP]:047D29778100C65A1DA1783716588DCE2B8B4AEE8E228F189638A90F22637337334B49DCB66A6DC8F9978ACA7648A943B0
  208:d=3  hl=2 l=  25 prim: INTEGER           :FFFFFFFFFFFFFFFFFFFFFFFF7A62D031C83F4294F640EC13
  235:d=3  hl=2 l=   1 prim: INTEGER           :01
  238:d=1  hl=2 l=  52 cons: cont [ 1 ]
  240:d=2  hl=2 l=  50 prim: BIT STRING
```
What you want is:
```
$ openssl asn1parse -inform DER -in test-namedcurve.priv.der
    0:d=0  hl=2 l=  95 cons: SEQUENCE
    2:d=1  hl=2 l=   1 prim: INTEGER           :01
    5:d=1  hl=2 l=  24 prim: OCTET STRING      [HEX DUMP]:C2F905E70DC1CB84E096AE45157AB0584F14CF2FC50E9C9C
   31:d=1  hl=2 l=  10 cons: cont [ 0 ]
   33:d=2  hl=2 l=   8 prim: OBJECT            :prime192v3
   43:d=1  hl=2 l=  52 cons: cont [ 1 ]
   45:d=2  hl=2 l=  50 prim: BIT STRING
```

And similarly for public keys - here is current long form:
```
$ openssl asn1parse -inform DER -in test-explicit.pub.der
    0:d=0  hl=4 l= 266 cons: SEQUENCE
    4:d=1  hl=3 l= 211 cons: SEQUENCE
    7:d=2  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   16:d=2  hl=3 l= 199 cons: SEQUENCE
   19:d=3  hl=2 l=   1 prim: INTEGER           :01
   22:d=3  hl=2 l=  36 cons: SEQUENCE
   24:d=4  hl=2 l=   7 prim: OBJECT            :prime-field
   33:d=4  hl=2 l=  25 prim: INTEGER           :FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFF
   60:d=3  hl=2 l=  75 cons: SEQUENCE
   62:d=4  hl=2 l=  24 prim: OCTET STRING      [HEX DUMP]:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFC
   88:d=4  hl=2 l=  24 prim: OCTET STRING      [HEX DUMP]:22123DC2395A05CAA7423DAECCC94760A7D462256BD56916
  114:d=4  hl=2 l=  21 prim: BIT STRING
  137:d=3  hl=2 l=  49 prim: OCTET STRING      [HEX DUMP]:047D29778100C65A1DA1783716588DCE2B8B4AEE8E228F189638A90F22637337334B49DCB66A6DC8F9978ACA7648A943B0
  188:d=3  hl=2 l=  25 prim: INTEGER           :FFFFFFFFFFFFFFFFFFFFFFFF7A62D031C83F4294F640EC13
  215:d=3  hl=2 l=   1 prim: INTEGER           :01
  218:d=1  hl=2 l=  50 prim: BIT STRING
```

And corresponding short form:
```
$ openssl asn1parse -inform DER -in test-namedcurve.pub.der
    0:d=0  hl=2 l=  73 cons: SEQUENCE
    2:d=1  hl=2 l=  19 cons: SEQUENCE
    4:d=2  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   13:d=2  hl=2 l=   8 prim: OBJECT            :prime192v3
   23:d=1  hl=2 l=  50 prim: BIT STRING
```

Basically the implementation should not be that complicated.

There some questions related to the interface:
* in `ecc_export_full` we will probably need dome special flag like `PK_CURVEOID` so that we can call it from `CryptX_PK_ECC.xs.inc` like this:
```
rv = ecc_export_full(out, &out_len, PK_PRIVATE|PK_CURVEOID, &self->key);
```
* then we will also need to somehow extend `export_key_der` interface - I do not know what is the best way, maybe adding the second parameter/flag (but we can decide this one at the end).

Anyway, I am reopening this issue in case you want to work on it.

**Comment by karel-m** [comment]
And to keep it consistent we should perhaps also support exporting short PEM form via `export_key_pem`

**Comment by manuelm** [comment]
Put together a working draft: https://github.com/DCIT/perl-CryptX/compare/master...manuelm:curve_oid_export (the diff is more horrible than the actual change).

The code includes a fixme about what to do if no OID is assigned. I think an OID lookup would be the best shot. If no OID can be found I can either bail out or fallback to the full format.

A newly generated curve by name seems to miss the OID too. I'll look into that now.

And of course tests :-)

**Comment by manuelm** [comment]
- Added OID lookup to `ecc_export_full` in case no OID is set
- Added new argument `oid` to `ecc_dp_set`
- Pass OID from input hash in `_ecc_set_dp_from_SV` to `ecc_dp_set` if available (allows setting OID directly from `Crypt::PK::ECC::generate_key` and co)

Only tests missing, imho.

**Comment by karel-m** [comment]
Your patch looks great. Good work.

Just some cosmetic issues:

* I would prefer using `private_short` + `public_short`

* please include also some documentation - my proposal:
```diff
--- a/lib/Crypt/PK/ECC.pm
+++ b/lib/Crypt/PK/ECC.pm
@@ -1027,12 +1027,26 @@ Import raw public/private key - can load data exported by L</export_key_raw>.
  #or
  my $public_der = $pk->export_key_der('public');

+Since CryptX-0.36 C<export_key_der> can also export keys in a format
+that does not explicitely contain curve parameters but only curve OID.
+
+ my $private_der = $pk->export_key_der('private_short');
+ #or
+ my $public_der = $pk->export_key_der('public_short');
+
 =head2 export_key_pem

  my $private_pem = $pk->export_key_pem('private');
  #or
  my $public_pem = $pk->export_key_pem('public');

+Since CryptX-0.36 C<export_key_pem> can also export keys in a format
+that does not explicitely contain curve parameters but only curve OID.
+
+ my $private_pem = $pk->export_key_pem('private_short');
+ #or
+ my $public_pem = $pk->export_key_pem('public_short');
+
 Support for password protected PEM keys
```

* ad tests 
  * unfortunately current coverage for `export_key_(pem|der)` is poor
  * there is something in `t/pk_ecc.t`
  * IMO in `pk_ecc.t` we should test:
 ```
 $pem = $pk1->export_key_pem('private'); $pk2->import_key(\$pem);
 $pem = $pk1->export_key_pem('public'); $pk2->import_key(\$pem);
 $pem = $pk1->export_key_pem('private_short'); $pk2->import_key(\$pem);
 $pem = $pk1->export_key_pem('public_short'); $pk2->import_key(\$pem);
# + perhaps the same with export_key_der(..)
```
  * on top of that it might be a good idea to turn `t/openssl/ecc-test.pl` into a regular test e.g. `t\pk_ecc_openssl_interoperability` (it can be turned off unless there is some ENV variable set)

**Comment by manuelm** [comment]
Thanks. I've already prepared some basic tests. Pushed them together with your documentation + renaming.

Will add some more tests and prepare a PR.

Re. https://github.com/DCIT/perl-CryptX/compare/master...manuelm:curve_oid_export#diff-f34f72b2dfcb3643461b784a4975dc81R115: Shall I bailout or fallback?

**Comment by karel-m** [comment]
> Re. https://github.com/DCIT/perl-CryptX/compare/master...manuelm:curve_oid_export#diff-f34f72b2dfcb3643461b784a4975dc81R115: Shall I bailout or fallback?

Bailout
