### ISSUE TITLE
Installer failed on macOS – Easy Workaround

### ISSUE THREAD

**Issue by jerrykrinock** [DCIT/perl-CryptX#22]
When I attempted to install on macOS 10.12,

```
cpan install Crypt::PRNG
```

installer failed because the `gzip` and `tar` programs are in `/usr/bin` instead of `/sw/bin`.  To work around that, create `/sw/bin` if necessary and then make symbolic links.

```
mkdir /sw
mkdir /sw/bin
ln -s /usr/bin/tar /sw/bin/tar
ln -s /usr/bin/gzip /sw/bin/gzip
```

**Comment by karel-m** [comment]
Hi,

I am afraid that this is related to your CPAN setup

Try:
* `cpan`
* `cpan> o conf`

You will probably see something like `tar    [/usr/bin/tar]` - that should be reconfigured in your case to `/sw/bin/tar`

Another option is to use a tool called `cpanm` AKA cpanminus simply:
* `cpanm Crypt::PRNG`

**Comment by jerrykrinock** [comment]
Thank you.  I was unaware of cpan config.  Issue is closed
