### ISSUE TITLE
RC2 does not support 40bit encryption

### ISSUE THREAD

**Issue by nlitsme** [DCIT/perl-CryptX#25]
Even though 40bits is far from sufficient to use in a real crypto application, there have been many cases where 40 bit keys were used.  for example in pkcs12 :  pbewithSHAAnd40BitRC2CBC 

I think it would be nice if the RC2 module did not reject small keysizes.

willem

**Comment by karel-m** [comment]
Try CryptX-0.041_002. The fix: d5a49f8d

**Comment by karel-m** [comment]
Try CryptX-0.041_003

**Comment by nlitsme** [comment]
works, thanks
