### ISSUE TITLE
crypt::cipher::rc6 or crypt::mode::cbc problem

### ISSUE THREAD

**Issue by zhou0** [DCIT/perl-CryptX#29]
when i use crypt::cipher::rc6 with crypt::mode::cbc , only part of data is processed .

**Comment by karel-m** [comment]
Could you please post here some code + test vectors which are failing?

**Comment by karel-m** [comment]
is this still a problem?

**Comment by zhou0** [comment]
because TLS 1.3 will drop CBC mode and move to AEAD , so I did not investigate this issue further.  CFB,CTR ,OFB and AEAD modes are used instead.

**Comment by karel-m** [comment]
> because TLS 1.3 will drop CBC mode and move to AEAD , so I did not investigate this issue further. CFB,CTR ,OFB and AEAD modes are used instead.

OK, I am closing this, feel free to open a new one
