### ISSUE TITLE
GCM: Missing aad_add and ecnrypt_add fails on Windows?

### ISSUE THREAD

**Issue by philippe44** [DCIT/perl-CryptX#36]
Hi - Using OO interface, the method aad_add cannot be found and calling encrypt_add("some data"), crashes with "invalid argument provided". Functional calls works fine

**Comment by karel-m** [comment]
Try adata_add instead of aad_add (documentation is misleading).

encrypt_add crashes when adata_add was not called before (I have to
investigate this one).

**Comment by karel-m** [comment]
The bug was introduced here
https://github.com/DCIT/perl-CryptX/commit/9e34032f57ae431a6df263fcaac8da1dc9a57c07

**Comment by karel-m** [comment]
Try CryptX-0.048_001 it should fix:
* encrypt_add crash when adata_add was not called before
* method `aad_add` was removed from doc of all EncAuth algorithms, the correct one is `adata_add`

**Comment by karel-m** [comment]
could you please check CryptX-0.048_002, if there is no feedback I am going to close this issue with coming 0.049 release

**Comment by philippe44** [comment]
Verified - Thank you
