### ISSUE TITLE
FATAL: find_hash failed for 

### ISSUE THREAD

**Issue by bsanil** [DCIT/perl-CryptX#53]
when I tried to use salt value using "pack" function I am getting below error:

**FATAL: find_hash failed for '' at eck.pm line 76.**

$hash_name = $hash_name||'SHA256';
$salt = pack("H*", "00" x Crypt::Digest->hashsize($hash_name));
my $hkdf_key = Crypt::KeyDerivation->hkdf($password, $salt);

even I tried to getting hash object by calling below function:
$hash_name = Crypt::Digest::_trans_digest_name($hash_name||'SHA256');

**Undefined subroutine &Crypt::Digest::_trans_digest_name called at eck.pm line 73.**

Please help, how can provide salt value.

**Comment by karel-m** [comment]
the wrong part is:
```perl
Crypt::KeyDerivation->hkdf($password, $salt);
```

it should be:
```perl
Crypt::KeyDerivation::hkdf($password, $salt);
```

or
```perl
use Crypt::KeyDerivation qw(hkdf);
# ...
my $hkdf_key = hkdf($password, $salt);
```
