### ISSUE TITLE
ISO 10126 padding CryptX::Mode::ECB

### ISSUE THREAD

**Issue by lilphil** [DCIT/perl-CryptX#54]
I am in the unfortunate situation that I need to be able to decrypt legacy data which is ECB, DES_EDE, padded with random bytes where the last byte is the padding boundary.

In version 0.061 of this module, we were able to use PKCS5 padding mode, and I think X923 too as it didn't check whether the extra bytes were as expected. However, from 0.062 it now uses padding_depad which is stricter.

After some research, it looks like libtomcrypt supports ISO 10126, which whilst this has been withdrawn I believe it fits our padding type. However the CryptX::Mode::ECB module does not make this padding mode available.

It would be super useful if this could be added.

Thanks!

**Comment by karel-m** [comment]
Could you please check current `master`?

If you find some spare time it would be nice if you can create a pull request with ISO 10126 testcase in `t/mode_ecb.t`

**Comment by lilphil** [comment]
Thanks for getting that in so fast! I've created a test, but as per the comment on the PR there's something wrong in the pad/depad functions causing it to fail.
