### ISSUE TITLE
export_key_jwk() doesn’t export canonical JSON

### ISSUE THREAD

**Issue by FGasper** [DCIT/perl-CryptX#6]
For creating JWK thumbprints it’s necessary to have canonical (i.e., sorted keys) JSON.

The JWK that this module exports, being non-canonical, is useless, which means it’s necessary to parse the JSON, then re-encode it canonically.

It would help this purpose—without breaking any others—if this module exported JWKs as canonical JSON. Could this be done?

**Comment by karel-m** [comment]
This one can be fixed quite easily - try https://github.com/DCIT/perl-CryptX/commit/33a6c68218ff6b532a936151d198945b5ee1b003

**Comment by karel-m** [comment]
some tests added in 6991bd9

IMO fixed & ready for release
