### ISSUE TITLE
Test fails using built-in Perl 5.18 on macOS Catalina

### ISSUE THREAD

**Issue by twogee** [DCIT/perl-CryptX#60]
Catalina does not allow relative paths to shared libraries, making `t/mbi_ltm_bigintg.t` fail. A possible fix is using `rel2abs`

```
#!/usr/bin/perl -w

use strict;
use Test;
use File::Spec::Functions 'rel2abs';

BEGIN {
    $| = 1;
    chdir 't' if -d 't';
    unshift @INC, rel2abs('../lib');             # for running manually
    unshift @INC, rel2abs('../blib/arch');       # for running manually
    plan tests => 356;
}
```

**Comment by karel-m** [comment]
could you please try
https://cpan.metacpan.org/authors/id/M/MI/MIK/CryptX-0.067_001.tar.gz

**Comment by twogee** [comment]
Passes all tests with Math::BigInt VERSION=1.999818, thank you!
