### ISSUE TITLE
Question - Alien libtom

### ISSUE THREAD

**Issue by brtastic** [DCIT/perl-CryptX#61]
Hello, thank you for this great module. I am using it in another CPAN distribution.

I want to depend on libtom entirely, together with Math::BigInt::LTM and some EC-point arithmetic I need in my algorithms. Right now I'm using yet another CPAN distro that implements it in perl, but with GMP support only. I'm basically pulling extra modules and using two math libraries at once, which seems very redundant.

I'm eager to write my own XS using libtom toolkit to get what I need out of it, but CryptX is not actually installing it in the system, just using the header files that come together with the distribution. As far as I know there's no sane way I can reuse that code in my distribution, so I'd have to bundle it myself the second time or ask users to install it beforehand.

Do you think it would be possible to change libtom bundling method to installation (Alien:: modules seem to do that), so that once installed it'll be available to all? That would be the ideal solution to me to depend on CryptX to install the library it's using, but I know that might not be the best idea from a module standpoint for a variety of reasons. 

I thought I'd ask here before I make any decisions on my own. I'm also open to suggestions on how it solve this problem.

edit: I see that there's an experimental condition in the makefile to use system libtom if envvars are set, so I guess some thought has been put into it already

**Comment by karel-m** [comment]
Hi, I do not plan to implement Alien::Libtom in near future. As you already noticed there are `$ENV{CRYPTX_CFLAGS}` and `$ENV{CRYPTX_LDFLAGS}` which can be used if you want to link with another libtomcrypt. But keep in mind that bundled libtomcrypt is from `develop` branch (containing some "not yet released" features like Ed25519).

**Comment by brtastic** [comment]
Thank you for your response! I know CryptX is using dev branch of libtomcrypt, as I have tried to do some work around it already. 
My XS ability is rather limited, but I think the biggest gain from using libtom directly would require hooking into internal `Crypt::PK::ECC` C structure to get the instance of libtom's `ecc_key` from there (so I wouldn't have to export and import it again in some cases). Since that seems impossible (or at least very hard) I'll leave the current gmp - tomcrypt setup be for now until I come up with something better.
