### ISSUE TITLE
ltc Licensing could be clearer

### ISSUE THREAD

**Issue by kentfredric** [DCIT/perl-CryptX#63]
Initially, when I tried to investigate this, I initially found a bunch of scary messages in my source grep which *seemed* to indicate that embedded code was *not* compatible with either "perl" license options.

But fortunately I talked to the right person and they pointed out some things that weren't easy to discover.

Namely, that despite there being a bit of a mess of licenses in src/, there is no license problem to speak of, as all the components are part of LibTomCrypt, and it has a very permissive license.

But a raw copy of LibTomCrypts license is not shipped with this, and there's no indication at the top level about the conditions that may/may not apply to bundled files.

Like, my grep context only showing: 

https://github.com/DCIT/perl-CryptX/blob/238c865807f3efc80c32e9a53b1c7e4f2591f81d/src/ltc/stream/rabbit/rabbit.c#L34-L49 

Looks rather startling to see. ( Being unlucky enough to find a declaration of what the license **was** is , well, awesome )

So my suggestion would be to:
1. Retain copies of LibTomCrypts [LICENSE](https://github.com/libtom/libtomcrypt/blob/develop/LICENSE), and others, as needed.
2. Include a notice indicating bundling LibTomCrypt and friends to license, such as:
```
This module also contains copies of LibTomCrypt (https://github.com/libtom/libtomcrypt),
which has a collection of aggregated 3rd party libraries,
all of which fall into public-domain usage licenses.
```

Or something along those lines.

**Comment by karel-m** [comment]
I have added:
* https://github.com/DCIT/perl-CryptX/blob/master/src/README.txt
* https://github.com/DCIT/perl-CryptX/blob/master/src/ltm/LICENSE
* https://github.com/DCIT/perl-CryptX/blob/master/src/ltc/LICENSE

Formally both LibTom project are now under http://unlicense.org/

Which is OSI approved license https://opensource.org/licenses/unlicense
