### ISSUE TITLE
Request: export_key_jwk_struct()

### ISSUE THREAD

**Issue by FGasper** [DCIT/perl-CryptX#7]
For creating JWS for the ACME protocol it’s useful to have a JWK in a data structure rather than in serialized format. Could a function for that be added here?

Thank you!

**Comment by karel-m** [comment]
You mean something like this?
```perl
sub export_key_jwkhash {
  decode_json(shift->export_key_jwk(@_));
}
```

**Comment by FGasper** [comment]
Yes, though it would seem cleaner to implement by refactoring `export_key_jwk()` to wrap the new `export_key_jwk_hash()` logic so that there’s not a useless encode/decode.

**Comment by FGasper** [comment]
Ah, I didn’t realize there was that flag there. Sorry!

**Comment by karel-m** [comment]
It seems to be also documented :) Anyway, it is already there.
