### ISSUE TITLE
CryptX fails to compile on AIX 6.1 64bits starting at version 0.56

### ISSUE THREAD

**Issue by sblondeel** [DCIT/perl-CryptX#71]
To compile old versions of CryptX I need to patch the Makefile produced by Makefile.PL as follows:

```bash
perl -i -pe 's{^AR =.*}{AR = ar -X64}; s{^FULL_AR =.*}{FULL_AR = /usr/bin/ar -X 64}; s{^LD =.*}{LD = ld -b64 -bnoquiet}' Makefile
```

(I added the -bnoquiet to understand why the linking failed; it is probably not necessary).

However, starting at version 0.56, the final link fails.

Attached are the passing tests logs for 055 and the final build error for 056.

Should I open another ticket for the missing options in the Makefile (-X64 for AR; -X 64 for FULL_AR; -b64 for ld)?

I slightly edited the logs to anonymise username and arch id.

[055-test-pass.txt](https://github.com/DCIT/perl-CryptX/files/6445563/055-test-pass.txt)
[056-build-error.txt](https://github.com/DCIT/perl-CryptX/files/6445564/056-build-error.txt)
[perl-V.txt](https://github.com/DCIT/perl-CryptX/files/6451071/perl-V.txt)
[gcc-v.txt](https://github.com/DCIT/perl-CryptX/files/6451073/gcc-v.txt)
[Makefile-diff.txt](https://github.com/DCIT/perl-CryptX/files/6456504/Makefile-diff.txt)
[Makefile-patch.txt](https://github.com/DCIT/perl-CryptX/files/6456505/Makefile-patch.txt)

**Comment by karel-m** [comment]
Could you please check the latest CryptX-0.081?

**Comment by sblondeel** [comment]
Unfortunately, I do not have access to that AIX platform any more. I trust you to have done what was needed though!
