### ISSUE TITLE
Tests failing for numbers with multiple underscore characters

### ISSUE THREAD

**Issue by pjacklam** [DCIT/perl-CryptX#76]
Math::BigInt and Math::BigFloat now accept numbers with multiple underscores in them. This is because they are accepted by Perl itself. For instance,
```
$ perl -le 'print 1__2'
12
```
When the following strings were given as input to Math::BigInt and Math::BigFloat, they used to result in a NaN. This is no longer the case.
```
1__2
1E1__2
11__2E2
0b__101
0x__123
123_
1__23
1_E12
```
I suggest that the test files t/mbi_ltm_bigfltpm.t and t/mbi_ltm_bigintpm.t are updated to reflect these changes.

**Comment by karel-m** [comment]
Thanks for notifying me.
