### ISSUE TITLE
new t/mbi_ltm_big*.t failures

### ISSUE THREAD

**Issue by eserte** [DCIT/perl-CryptX#82]
On some of my smokers:
```
#   Failed test '$x = Math::BigFloat->new("0"); $y = Math::BigFloat->new("10"); $x->bcos($y);'
#   at ./t/mbi_ltm/bigfltpm.inc line 168.
#          got: '1.000000000'
#     expected: '1'

#   Failed test '$x = Math::BigFloat->new("0"); $y = Math::BigFloat->new("20"); $x->bcos($y);'
#   at ./t/mbi_ltm/bigfltpm.inc line 168.
#          got: '1.0000000000000000000'
#     expected: '1'
Argument "" isn't numeric in subtraction (-) at /home/cpansand/.cpan/build/2022051619/Math-BigInt-1.999831-eT1LCZ/blib/lib/Math/BigFloat.pm line 4598, <DATA> line 330.
Argument "" isn't numeric in subtraction (-) at /home/cpansand/.cpan/build/2022051619/Math-BigInt-1.999831-eT1LCZ/blib/lib/Math/BigFloat.pm line 4598, <DATA> line 331.
Argument "" isn't numeric in subtraction (-) at /home/cpansand/.cpan/build/2022051619/Math-BigInt-1.999831-eT1LCZ/blib/lib/Math/BigFloat.pm line 4598, <DATA> line 332.
Argument "abc" isn't numeric in subtraction (-) at /home/cpansand/.cpan/build/2022051619/Math-BigInt-1.999831-eT1LCZ/blib/lib/Math/BigFloat.pm line 4598, <DATA> line 333.
# Looks like you failed 2 tests of 2408.
t/mbi_ltm_bigfltpm.t ................ 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/2408 subtests 
	(less 1 skipped subtest: 2405 okay)
...
#   Failed test 'blog(100)'
#   at t/mbi_ltm_biglog.t line 123.
#          got: '100'
#     expected: '2'
# Looks like you failed 1 test of 71.
t/mbi_ltm_biglog.t .................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/71 subtests 
```

Maybe caused by a change in the latest Math::BigInt (@pjacklam FYI)

**Comment by michal-josef-spacek** [comment]
Maybe we could move requires to Math::BigInt with version to test requires.

**Comment by karel-m** [comment]
Should be fixed in CryptX-0.076_001

**Comment by abraxxa** [comment]
Please add the fix to the Changes file, thanks!

**Comment by pjacklam** [comment]
The first failing case,
```
$x = Math::BigFloat->new("0"); $y = Math::BigFloat->new("10"); $x->bcos($y);
```
is a bug fix. The output from bcos() was not rounded when the result was zero. I assume the original author didn't round zero because rounding zero doesn't change the value. However, calling round() also sets the accuracy/precision of the object, which affects both output and later computations. So for consistency, the output of bcos() is now always rounded. That's why the output is now "1.000000000" rather than just "1".

**Comment by pjacklam** [comment]
The last case,
```
$x = Math::BigFloat::blog(Math::BigInt->new(100),10)
```
is worse. While I am encouraging users to switch to method calls rather than function calls, this should still have returned 2, not 100. I need to look further into that. Fortunately, the method call
```
$x = Math::BigFloat->blog(Math::BigInt->new(100),10)
```
gives the correct answer.

**Comment by jkeenan** [comment]
AFAICT, the [most recent CPAN production release of CryptX](https://metacpan.org/pod/CryptX) was on Jan 07 2022.  So while the issue may be patched on GitHub, we don't yet have a new release for final testing.  Do you know when that will be issued?

**Comment by karel-m** [comment]
> ... we don't yet have a new release for final testing. Do you know when that will be issued?

CryptX-0.077 released

**Comment by jkeenan** [comment]
> > ... we don't yet have a new release for final testing. Do you know when that will be issued?
> 
> CryptX-0.077 released

All tests now PASS when installed against perl-5.36.0 and against blead.  Thanks for your continued maintenance of this codebase.
