### ISSUE TITLE
Publish releases to enable subscribing

### ISSUE THREAD

**Issue by eric-j-ason** [DCIT/perl-CryptX#91]
Currently, [tags](https://github.com/DCIT/perl-CryptX/tags) are created, but not [releases](https://github.com/DCIT/perl-CryptX/releases), when a new version is made available. Releases would be useful, as you can get notifications from GitHub when a new one is out.

**Comment by karel-m** [comment]
https://github.com/DCIT/perl-CryptX/releases

**Comment by eric-j-ason** [comment]
Excellent, thank you!
